[package]
name = "gtk-layer-shell"
version = "0.1.0"
authors = ["pentamassiv <pentamassiv@posteo.de>"]
edition = "2018"
license = "MIT"
description = "Save gir-generated wrapper for gtk-layer-shell"
repository = "https://github.com/grelltrier/gtk-layer-shell-gir/tree/master/gtk-layer-shell-sys"
keywords = ["gtk", "gtk-layer-shell", "wayland", "gir", "wrapper"]
categories = ["api-bindings", "gui"]

[dependencies]
libc = "0.2"
bitflags = "1.0"

[dependencies.gtk-layer-shell-sys]
path = "./gtk-layer-shell-sys"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys" # all gtk-rs sys crates are in the sys repository

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk"
features= ["v3_22"]

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"