[package]
name = "gtk-layer-shell"
version = "0.1.0"
authors = ["pentamassiv <pentamassiv@posteo.de>"]
edition = "2018"

[dependencies]
libc = "0.2"
bitflags = "1.0"

[dependencies.gtk-layer-shell-sys]
path = "./gtk-layer-shell-sys"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys" # all gtk-rs sys crates are in the sys repository

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk"
features= ["v3_22"]

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"